dropbox/kaiken

CHANGELOG.md
README.md
RELEASING.md
build.gradle
gradle.properties

Actually preparing for release 1.0.2. There were to copies of the POM properties, one under build.gradle/ext{} that was used by the old Chris Bane script. And then the new one under gradle.properties which is that the new gradle plugin uses. Remove the old one and update release instructions.

Prepare for release 1.0.2.

---

integration-tests/src/androidTest/java/com/dropbox/kaiken/integration_tests/TestKaikenTestRule.kt
testing/api/testing.api
testing/gradle.properties
testing/src/main/java/com/dropbox/kaiken/testing/KaikenTestRule.kt

I only need one override across all the tests in one class in my dbapp feature, so I wanted to be able to specify a default override at Rule construction. Also updated the relevant test to demonstrate the usage of the secondary constructor.
Please let me know if there are any issues or suggestions!

Test Rule revision

---

scoping/build.gradle
scoping/src/androidTest/java/com/dropbox/kaiken/scoping/AuthAwareActivitiesTest.kt
scoping/src/androidTest/java/com/dropbox/kaiken/scoping/AuthAwareBroadcastReceiverTest.kt
scoping/src/androidTest/java/com/dropbox/kaiken/scoping/AuthAwareFragmentTest.kt
scoping/src/androidTest/java/com/dropbox/kaiken/scoping/AuthScopeOwnersFragmentsTest.kt
scoping/src/androidTest/java/com/dropbox/kaiken/scoping/LaunchActivitiesTestUtils.kt
scoping/src/androidTest/java/com/dropbox/kaiken/scoping/LaunchFragmentsTestUtils.kt
scoping/src/debug/java/test/com/dropbox/kaiken/scoping/TestAuthRequireBroadcastReceived.kt
testing/build.gradle
testing/src/debug/AndroidManifest.xml
testing/src/debug/java/test/com/dropbox/kaiken/testing/MyDependencies.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestActivity.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthAwareBroadcastReceiver.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthAwareFragment.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthAwareScopedActivity.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthAwareScopedFragment.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthOptionalActivity.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthOptionalBroadcastReceiver.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthOptionalFragment.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthRequireBroadcastReceived.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthRequiredActivity.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthRequiredBroadcastReceiver.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestAuthRequiredFragment.kt
testing/src/debug/java/test/com/dropbox/kaiken/testing/TestSimpleActivity.kt

Moving some test Activities and Fragments into the testing module so they can be used by clients.
Closes #17

Moving test classes to testing module

---

integration-tests/build.gradle
integration-tests/src/androidTest/java/com/dropbox/kaiken/integration_tests/runtime/TestInjectableAnnotation.kt
integration-tests/src/androidTest/java/com/dropbox/kaiken/integration_tests/testing/TestKaikenTestRule.kt
integration-tests/src/androidTest/java/com/dropbox/kaiken/integration_tests/testing/TestKaikenTestRuleComponentAsInjectorHolder.kt
integration-tests/src/androidTest/java/com/dropbox/kaiken/integration_tests/testing/TestKaikenTestRule_AuthAwareFragment.kt
integration-tests/src/debug/java/com/dropbox/kaiken/integration_tests/TestAuthAwareFragment.kt
integration-tests/src/debug/java/com/dropbox/kaiken/integration_tests/TestInjectorHolderActivity.kt
integration-tests/src/debug/java/com/dropbox/kaiken/integration_tests/TestInjectorHolderFragment.kt
integration-tests/src/debug/java/com/dropbox/kaiken/integration_tests/TestInjectorHolderFragmentWithDagger.kt
integration-tests/src/debug/java/com/dropbox/kaiken/integration_tests/TestSimpleFragment.kt
scoping/src/androidTest/java/com/dropbox/kaiken/scoping/AuthAwareBroadcastReceiverTest.kt
scoping/src/androidTest/java/com/dropbox/kaiken/scoping/AuthAwareFragmentTest.kt
scoping/src/androidTest/java/com/dropbox/kaiken/scoping/AuthScopeOwnersFragmentsTest.kt
scoping/src/androidTest/java/com/dropbox/kaiken/scoping/ViewingUserSelectorTest.kt
scoping/src/test/java/com/dropbox/kaiken/scoping/UserServicesProviderTest.kt

There is a bit of noise because I had to change the message to lateinit and that made me replace `isNull` by `isEmpty`. Please ignore that.
The important files to check are `TestInjectorHolderFragmentWithDagger` the `InjectHolder` is a `TestComponent` which is a Dagger generated class. This is similar to how we use it internally.
The test file is `TestKaikenTestRuleComponentAsInjectorHolder`

Add test case where injector holder is a Dagger component

---

scoping/src/main/java/com/dropbox/kaiken/scoping/AuthAwareScopeOwnerActivity.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/internal/AuthHelperStore.kt

- Remove assumptions that the AuthAwareScopeOwnerActivity is a FragmentActivity so that Kaiken can work with compose

Support ComponentActivity

---

build.gradle
dependencies.gradle
gradle/wrapper/gradle-wrapper.properties
integration-tests/build.gradle
runtime/api/runtime.api
scoping-navgraph/api/scoping-navgraph.api
scoping/api/scoping.api
testing/api/testing.api

This feature requires a newer version of AGP, which itself requires a newer version of Gradle. Both dependencies have been upgraded as well.

Upgrade Anvil and use the built-in mechanism to sync sources. 

---

README.md
gradle.properties
runtime/src/main/java/com/dropbox/kaiken/runtime/FragmentHelper.kt
runtime/src/main/java/com/dropbox/kaiken/runtime/InjectorHolder.kt
runtime/src/main/java/com/dropbox/kaiken/runtime/KaikenRuntimeTestUtils.kt

Currently, we're checking the `BuildConfig.DEBUG` flag if we should be reading from the injector factor and injector overrides. This code works if you're running the code using the debug variant of Kaiken, however, as code published to Maven Central is the `release` variant, this check will always fail.
These overrides are only set in the `testing` module and there's a check to ensure `require(testMode)` passes before we allow the overrides to be set.

Remove guards on injector read

---

gradle.properties

When we run the publish action, it fails in dokka hitting OOM https://github.com/dropbox/kaiken/runs/4243132113?check_suite_focus=true#step:4:1193
The issue in https://github.com/Kotlin/dokka/issues/1405 suggests to increase the memory to 2g

Increase metaspace memory for Gradle

---

.github/workflows/ci_test_and_publish.yml

Uses the vannitech Gradle Publish Plugin to automatically close and release artifacts in Nexus https://github.com/vanniktech/gradle-maven-publish-plugin#releasing

Automatically close and release in Nexus for releases

---

.github/workflows/ci_test_and_publish.yml

It's potentially unsafe to have code automatically pushed into the repo and we need to give the actions bot write permissions to the repo

Remove autocommit code

---

build.gradle
processor/src/main/java/com/dropbox/kaiken/processor/InjectableCodeGenerator.kt
processor/src/main/java/com/dropbox/kaiken/processor/InjectableFragmentWriter.kt
scoping-navgraph/api/scoping-navgraph.api
scoping/api/scoping.api
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthAwareBroadcastReceiver.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthAwareFragment.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthAwareScopeOwnerActivity.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthAwareScopeOwnerFragment.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthOptionalActivity.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthOptionalBroadcastReceiver.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthOptionalFragment.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthRequiredActivity.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthRequiredBroadcastReceiver.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthRequiredFragment.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/UserServicesProvider.kt
skeleton/api/skeleton.api
skeleton/src/main/java/com/dropbox/kaiken/skeleton/core/KaikenAppServices.kt
skeleton/src/test/java/com/dropbox/kaiken/skeleton/scoping/fugazi/FakeCoroutineScopes.kt

Turns on `allWarningsAsErrors = true` in an `allProjects` block. 
Most of the errors were around a `JvmDefault` which we already have as a `-Xjvm-default=compatibility`.

Treat kotlin compiler warnings as errors

---

CHANGELOG.md
README.md
gradle.properties

- revert to 1.8 (#129)
- revert kotlin (#126)
- Fixes issue with JvmDefault (#125)
- Update to latest parcelize (#114)

Prepare for release 2.0.4

---

scoping/src/main/java/com/dropbox/kaiken/scoping/ViewingUserSelector.kt

NavDeepLink nests the extras in a separate bundle. This diff adds ability to extract viewing user selector from that inner bundle

Get viewing selector to work well with NavDeepLink

---

gradle.properties

We've been iterating quickly and changing APIs frequently. 
For the moment, we'll shift to a 3.0.0 release branch and append with `alpha##` to avoid noise.  
These builds should be treated as untested and will potentially have breaking APIs changes.

Prepare for 3.0.0-alpha01 release

---

gradle.properties

Our CI script is finding `VERSION_NAME` and due to the commented out code there, it is borking on it.

Fix version in gradle.properties

---

.github/workflows/ci_test_and_publish.yml
build.gradle

Using Gradle to get the `VERSION_NAME` that Gradle is using to publish the artifact is a safer option than trying to roll our own parsing of properties files.  This should offer a super simple fix without the risk of future breaks due to someone forgetting this weird gotcha.

Adds  task to future-proof CI reads of version name.

---

LICENSE.txt
README.md

Making the license a plain text file that matches a standard license format allows Github to parse it to add metadata to the repository like this:
And more helpful information like this:

Rename and update license to its parsable by Github.

---

scoping/src/main/java/com/dropbox/kaiken/scoping/internal/AuthHelperStore.kt

BuildConfig.DEBUG is hard coded to false when we release to Maven.  
If consumers use this, they won't be able to override for their tests as it in a release.  
I think this does give the option that a consumer also abuses this functionality at runtime and uses it in production, but we'd need to refactor some code and extract things into another `scoping-test-util` module or similar.

Remove BuildConfig.DEBUG for AuthHelperStore

---

skeleton/src/main/java/com/dropbox/kaiken/skeleton/core/KaikenUserServicesProvider.kt
skeleton/src/test/java/com/dropbox/kaiken/skeleton/core/KaikenUserServicesProviderTest.kt

We were seeing an issue in the following scenario:
1) Launch an app and log in
2) Background the app, but do not close it
3) Launch Android Settings page and adjust permissions for the app
4) Open the app
Observed: App hangs at splash screen and does not proceed
By converting the cold stream into a hot stream w/ `shareIn` on the app coroutine scope, we're able to always monitor for content and resolve this issue.

Fix issue loading user on process recreate

---

sample/sample-with-di/app/src/main/java/com/dropbox/kaiken/sample/advancedsample/app/AdvancedKaikenSampleApplication.kt
skeleton-components/api/skeleton-components.api
skeleton-components/src/main/java/com/dropbox/kaiken/skeleton/components/scoping/Components.kt
skeleton-components/src/main/java/com/dropbox/kaiken/skeleton/core/KaikenConfig.kt
skeleton-components/src/test/java/com/dropbox/kaiken/skeleton/scoping/fugazi/FakeSkeletonConfig.kt

Binding the userId worked for sample apps, but we will need the SkeletonUser for production apps

Bind SkeletonUser instead of UserId with Anvil Components

---

processor/src/main/java/com/dropbox/kaiken/processor/InjectableActivityWriter.kt
processor/src/main/java/com/dropbox/kaiken/processor/InjectableCodeGenerator.kt
processor/src/main/java/com/dropbox/kaiken/processor/InjectableFragmentWriter.kt
processor/src/main/java/com/dropbox/kaiken/processor/internal/InjectableSharedWriter.kt
scoping/build.gradle

This PR fixes two issues
1. Previously, when using `Class.forName` in the generator, if the scope wasn't in the classpath the generator would fail. This meant you could not provide custom scopes and only use the ones built into kaiken
2. Anvil has an issue with multiple `@ContributesTo` bindings existing for the same class. This moves the generator to build out separate classes until we update to the latest version of Anvil (https://github.com/square/anvil/issues/236) which should now support this without the multiple class hack

Fix generator to allow scopes outside classpath and multiple bindings

---

scoping-navgraph/api/scoping-navgraph.api
scoping/api/scoping.api
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthOptionalActivity.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthOptionalFragment.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthRequiredActivity.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/AuthRequiredFragment.kt
scoping/src/main/java/com/dropbox/kaiken/scoping/UserProvider.kt
skeleton-components/api/skeleton-components.api
skeleton-components/src/main/java/com/dropbox/kaiken/skeleton/components/scoping/Components.kt

Having a `UserProvider` provides us two benefits
1. We have a common way of seeing if we have a user. Just check `if (user == null)`
2. We can use that logic internally to create a smarter injector factory

Add UserProvider
